In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print("Array:", arr)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)
print("type:", type(arr))

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim: 1
shape: (12,)
size: 12
dtype: int64
type: <class 'numpy.ndarray'>


In [2]:
import numpy as np

arr = np.arange(18).reshape(6,3)

print(arr)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)
print("type:", type(arr))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
ndim: 2
shape: (6, 3)
size: 18
dtype: int64
type: <class 'numpy.ndarray'>


In [3]:
import numpy as np

arr = np.arange(24).reshape(3,4,2)

print(arr)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)
print("type:", type(arr))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
ndim: 3
shape: (3, 4, 2)
size: 24
dtype: int64
type: <class 'numpy.ndarray'>


In [4]:
import numpy as np

arr = np.arange(48).reshape(2,4,6)

print(arr)
print("Number of dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]]]
Number of dimensions: 3
Shape: (2, 4, 6)
Size: 48
Data type: int64
